version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://booking_user:strongpassword@db:5432/booking_db

volumes:
  postgres_data: